apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: ginflix
  labels:
    app: mongo
spec:
  clusterIP: None
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: ginflix-backend
  namespace: ginflix
spec:
  type: NodePort
  selector:
    app: ginflix-backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ginflix-streamer
  namespace: ginflix
spec:
  type: NodePort
  selector:
    app: ginflix-streamer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30082
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ginflix-frontend
  namespace: ginflix
spec:
  type: NodePort
  selector:
    app: ginflix-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ginflix-frontend-admin
  namespace: ginflix
spec:
  type: NodePort
  selector:
    app: ginflix-frontend-admin
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30083
      protocol: TCP
