apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: garage
  namespace: ginflix
spec:
  serviceName: garage
  replicas: 1
  selector:
    matchLabels:
      app: garage
  template:
    metadata:
      labels:
        app: garage
    spec:
      initContainers:
        - name: init-garage-dirs
          image: busybox:1.36
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - mkdir -p /var/lib/garage/meta /var/lib/garage/data
          volumeMounts:
            - name: garage-data
              mountPath: /var/lib/garage
      containers:
        - name: garage
          image: dxflrs/amd64_garage:v0.7.0-rc1
          imagePullPolicy: IfNotPresent
          ports:
            - name: s3
              containerPort: 3900
            - name: rpc
              containerPort: 3901
            - name: web
              containerPort: 3902
          volumeMounts:
            - name: garage-config
              mountPath: /etc/garage.toml
              subPath: garage.toml
            - name: garage-data
              mountPath: /var/lib/garage
      volumes:
        - name: garage-config
          configMap:
            name: garage-config
  volumeClaimTemplates:
    - metadata:
        name: garage-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: ginflix
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
              name: mongodb
          args:
            - --replSet
            - rs0
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
