apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ginflix-backend
  namespace: ginflix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ginflix-backend
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ginflix-streamer
  namespace: ginflix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ginflix-streamer
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
