apiVersion: v1
kind: Namespace
metadata:
  name: ginflix
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ginflix-config
  namespace: ginflix
data:
  MONGO_URI: mongodb://mongo-0.mongo.ginflix.svc.cluster.local:27017/ginflix
  GARAGE_ENDPOINT: 137.194.210.140:3900
  GARAGE_BUCKET: bucket11
  GARAGE_USE_SSL: "false"
  AUTH_DISABLED: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: ginflix-garage-credentials
  namespace: ginflix
type: Opaque
stringData:
  GARAGE_ACCESS_KEY: GK6e76c3622af80c60e1bce247
  GARAGE_SECRET_KEY: 607a136544de9f60629e07a692c0c5e446d3eb7d22e4d5b6df3c4de66d8d62de
---
