apiVersion: v1
kind: Namespace
metadata:
  name: ginflix
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ginflix-config
  namespace: ginflix
data:
  BACKEND_URL_PUBLIC: http://localhost:30081
  STREAM_URL_PUBLIC: http://localhost:30082
  BACKEND_URL_INTERNAL: http://ginflix-backend-svc.ginflix.svc.cluster.local:8080
  STREAM_URL_INTERNAL: http://ginflix-streamer-svc.ginflix.svc.cluster.local:8080
  MONGO_URI: mongodb://ginflix-mongo-0.ginflix-mongo.ginflix.svc.cluster.local:27017/ginflix
  GARAGE_BUCKET: ginflix-media
  GARAGE_ENDPOINT: garage-service.ginflix.svc.cluster.local:3901
  GARAGE_USE_SSL: "false"
  AUTH_DISABLED: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: ginflix-secrets
  namespace: ginflix
type: Opaque
stringData:
  GARAGE_ACCESS_KEY: GK98caf7a206f7236efbaf7fbe
  GARAGE_SECRET_KEY: 5355b15d79ea2cf6a88f0c09462bfdbd41d6352bb238d5c97a398343dc39fefa
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ginflix-garage-data
  namespace: ginflix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: garage-config
  namespace: ginflix
data:
  garage.toml: |
    metadata_dir = "/data/meta"
    data_dir = "/data/data"

    replication_mode = "none"

    rpc_bind_addr = "0.0.0.0:3900"
    rpc_public_addr = "garage-service.ginflix.svc.cluster.local:3900"
    rpc_secret = "ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb"

    [s3_api]
    s3_region = "garage"
    api_bind_addr = "0.0.0.0:3901"
    root_domain = ".s3.garage.local"

    [s3_web]
    bind_addr = "0.0.0.0:3902"
    root_domain = ".web.garage.local"
---
apiVersion: v1
kind: Service
metadata:
  name: garage-service
  namespace: ginflix
spec:
  selector:
    app: garage
  ports:
    - name: api
      port: 3901
      targetPort: 3901
    - name: web
      port: 3902
      targetPort: 3902
    - name: rpc
      port: 3900
      targetPort: 3900
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: garage
  namespace: ginflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garage
  template:
    metadata:
      labels:
        app: garage
    spec:
      containers:
        - name: garage
          image: dxflrs/garage:v0.9.4
          command: ["/garage", "--config", "/etc/garage/garage.toml", "server"]
          args: []
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 3900
              name: rpc
            - containerPort: 3901
              name: api
            - containerPort: 3902
              name: web
          volumeMounts:
            - name: garage-data
              mountPath: /data
            - name: garage-config
              mountPath: /etc/garage/garage.toml
              subPath: garage.toml
          readinessProbe:
            tcpSocket:
              port: 3901
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3901
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: garage-data
          persistentVolumeClaim:
            claimName: ginflix-garage-data
        - name: garage-config
          configMap:
            name: garage-config
---
apiVersion: v1
kind: Service
metadata:
  name: ginflix-mongo
  namespace: ginflix
  labels:
    app: ginflix-mongo
spec:
  clusterIP: None
  selector:
    app: ginflix-mongo
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: ginflix-mongo-svc
  namespace: ginflix
  labels:
    app: ginflix-mongo
spec:
  selector:
    app: ginflix-mongo
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ginflix-mongo
  namespace: ginflix
spec:
  serviceName: ginflix-mongo
  replicas: 1
  selector:
    matchLabels:
      app: ginflix-mongo
  template:
    metadata:
      labels:
        app: ginflix-mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: mongo
              containerPort: 27017
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          env:
            - name: MONGO_INITDB_DATABASE
              value: ginflix
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ginflix-backend
  namespace: ginflix
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ginflix-backend
  template:
    metadata:
      labels:
        app: ginflix-backend
    spec:
      containers:
        - name: backend
          image: ginflix-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: ginflix-config
                  key: MONGO_URI
            - name: GARAGE_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: ginflix-config
                  key: GARAGE_BUCKET
            - name: GARAGE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: ginflix-config
                  key: GARAGE_ENDPOINT
            - name: GARAGE_USE_SSL
              valueFrom:
                configMapKeyRef:
                  name: ginflix-config
                  key: GARAGE_USE_SSL
            - name: GARAGE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: ginflix-secrets
                  key: GARAGE_ACCESS_KEY
            - name: GARAGE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ginflix-secrets
                  key: GARAGE_SECRET_KEY
            - name: AUTH_DISABLED
              valueFrom:
                configMapKeyRef:
                  name: ginflix-config
                  key: AUTH_DISABLED
            - name: STREAM_URL
              valueFrom:
                configMapKeyRef:
                  name: ginflix-config
                  key: STREAM_URL_INTERNAL
---
apiVersion: v1
kind: Service
metadata:
  name: ginflix-backend-svc
  namespace: ginflix
spec:
  type: NodePort
  selector:
    app: ginflix-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30081
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ginflix-backend-hpa
  namespace: ginflix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ginflix-backend
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ginflix-streamer
  namespace: ginflix
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ginflix-streamer
  template:
    metadata:
      labels:
        app: ginflix-streamer
    spec:
      containers:
        - name: streamer
          image: ginflix-streamer:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: ginflix-config
                  key: BACKEND_URL_INTERNAL
            - name: STREAM_URL
              valueFrom:
                configMapKeyRef:
                  name: ginflix-config
                  key: STREAM_URL_INTERNAL
            - name: GARAGE_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: ginflix-config
                  key: GARAGE_BUCKET
            - name: GARAGE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: ginflix-config
                  key: GARAGE_ENDPOINT
            - name: GARAGE_USE_SSL
              valueFrom:
                configMapKeyRef:
                  name: ginflix-config
                  key: GARAGE_USE_SSL
            - name: GARAGE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: ginflix-secrets
                  key: GARAGE_ACCESS_KEY
            - name: GARAGE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ginflix-secrets
                  key: GARAGE_SECRET_KEY
            - name: AUTH_DISABLED
              valueFrom:
                configMapKeyRef:
                  name: ginflix-config
                  key: AUTH_DISABLED
---
apiVersion: v1
kind: Service
metadata:
  name: ginflix-streamer-svc
  namespace: ginflix
spec:
  type: NodePort
  selector:
    app: ginflix-streamer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30082
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ginflix-streamer-hpa
  namespace: ginflix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ginflix-streamer
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ginflix-frontend
  namespace: ginflix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ginflix-frontend
  template:
    metadata:
      labels:
        app: ginflix-frontend
    spec:
      containers:
        - name: frontend
          image: ginflix-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          env:
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: ginflix-config
                  key: BACKEND_URL_PUBLIC
            - name: STREAM_URL
              valueFrom:
                configMapKeyRef:
                  name: ginflix-config
                  key: STREAM_URL_PUBLIC
            - name: AUTH_DISABLED
              valueFrom:
                configMapKeyRef:
                  name: ginflix-config
                  key: AUTH_DISABLED
---
apiVersion: v1
kind: Service
metadata:
  name: ginflix-frontend-svc
  namespace: ginflix
spec:
  type: NodePort
  selector:
    app: ginflix-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: ginflix-frontend-admin-svc
  namespace: ginflix
spec:
  type: NodePort
  selector:
    app: ginflix-frontend-admin
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30083
